worker_processes 1;

events{
    worker_connections 1024;
}

http{
    include mime.types;
    default_type  application/octet-stream;

    upstream nodejs_cluster{
        least_conn;
        server 127.0.0.1:8001;
        server 127.0.0.1:8002;
        server 127.0.0.1:8003;
    }
    server{
        listen 8020;
        server_name localhost;

        location /api/ {
            proxy_pass http://nodejs_cluster/api/;
            proxy_set_header HOST $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
            root C:/Fullstack_NGINX/frontend/dist;
            index index.html;
            try_files $uri /index.html;
        }
    }
  
}